config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:destroy]
  get "home/index"

  root "posts#index"

  get "/settings", to: "users#settings", as: :settings
  
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, param: :username
  resources :users, only: [:show]
  resources :likes, only: [:create] do
    collection do
      delete 'destroy', to: 'likes#destroy'
    end
  end
  resources :follows, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_one_attached :avatar
  has_many :posts
  has_many :comments

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :active_follows, class_name: "Follow", 
                            foreign_key: "follower_id",
                            dependent: :destroy
  has_many :following, through: :active_follows, source: :followed

  has_many :passive_follows, class_name: "Follow", 
                             foreign_key: "followed_id",
                             dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  validates :username, presence: true,
            uniqueness: true,
            length: { maximum: 24 },
            format: { with: /\A[a-z0-9]+\z/, message: "must be a unique 24 length lowercase latin/number value" }

  validates :email, presence: true, 
            uniqueness: true,
            format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must contain '@'" }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    
    if login
      where(conditions.to_h).where(
        ["lower(username) = :value OR lower(email) = :value", 
        { value: login.downcase }]
      ).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def to_param
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(username: params[:username])
    @posts = @user.posts.select(:id).order(created_at: :desc)
      .paginate(page: params[:page], per_page: 20).with_attached_image
    @followed = current_user.active_follows.exists?(followed_id: @user.id)

    @posts_count = @user.posts.size
    @followers_count = @user.followers.size
    @following_count = @user.following.size
  end

  def index
    @users = User.all.paginate(page: params[:page], per_page: 20)
  end

  def settings
  end
end

app/views/users/index.html.erb
<% content_for :page_title, "People" %>

<%= render 'shared/left_panel' %>
<div class="content-posts" style="padding-top: 40px; border-radius: 8px;">
  <% @users.each do |user| %>
    <div class="settings-elem">
      <%= link_to user_path(user), class: "person" do %>
        <%= user.username %>
      <% end %>
    </div>
  <% end %>
  <%= will_paginate @users, class: "pagination" %>
</div>

app/views/users/settings.html.erb
<% content_for :page_title, "Settings" %>

<%= render 'shared/left_panel' %>
<div class="content-posts" style="padding-top: 40px; border-radius: 8px;">
  <div class="settings-elem">
    <p>Sign out?</p>
    <%= button_to "Sign out", destroy_user_session_path, 
                method: :delete, 
                form_class: "inline-form", 
                class: "button" %>
  </div>
  
</div>

app/views/users/show.html.erb
<% content_for :page_title, "Profile" %>

<%= render 'shared/left_panel' %>
<div class="content-posts" style="padding-top: 24px">
  <div class="user-show-info">
    <%= image_tag "profile.svg", alt: "profile image", style: "height: 192px; background: inherit" %>
    <div class="user-show-text-info" data-controller="follow" data-follow-username-value="<%= @user.username %>">
      <div class="user-show-username-button">
        <div class="user-show-username">
          <%= @user.username %>
        </div>
        <% if current_user != @user %>
          <%= check_box_tag "follow_toggle_#{@user.username}", "1", @followed,
                  id: "follow-toggle-#{@user.username}", class: "hidden-checkbox",
                  data: { action: "change->follow#toggle" } %>
            <label for="follow-toggle-<%= @user.username %>" class="button" id="follow-button">
              <% if @followed %>
                Unfollow
              <% else %>
                Follow
              <% end %>
            </label>
        <% else %>
          <%= link_to new_post_path, class: "link" do %>
            New post
          <% end %>
        <% end %>
      </div>
      <div class="user-show-related-info-panel">
        <div class="user-show-related-info-item"><%= @posts_count %> posts</div>
        <div class="user-show-related-info-item" data-follow-target="count"><%= @followers_count %> followers</div>
        <div class="user-show-related-info-item"><%= @following_count %> following</div>
      </div>
    </div>   
  </div>
  <div class="posts-grid">
    <% @posts.each do |post| %>
      <% if post.image.attached? %>
        <%= link_to post_path(post), class: "user-post-image" do %>
          <%= image_tag post.image, alt: "Post ##{post.id}" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <%= will_paginate @posts, class: "pagination" %>
</div>