config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:destroy]
  get "home/index"

  root "posts#index"

  get "/settings", to: "users#settings", as: :settings
  
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, param: :username
  resources :users, only: [:show]
  resources :likes, only: [:create] do
    collection do
      delete 'destroy', to: 'likes#destroy'
    end
  end
  resources :follows, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :image, presence: true
  validates :description, length: { maximum: 200 }
  validate :image_format

  private

  def image_format
    if image.attached? && !image.content_type.in?(%('image/jpeg image/png'))
      errors.add(:image, 'must be a JPEG or PNG')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_one_attached :avatar
  has_many :posts
  has_many :comments

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :active_follows, class_name: "Follow", 
                            foreign_key: "follower_id",
                            dependent: :destroy
  has_many :following, through: :active_follows, source: :followed

  has_many :passive_follows, class_name: "Follow", 
                             foreign_key: "followed_id",
                             dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  validates :username, presence: true,
            uniqueness: true,
            length: { maximum: 24 },
            format: { with: /\A[a-z0-9]+\z/, message: "must be a unique 24 length lowercase latin/number value" }

  validates :email, presence: true, 
            uniqueness: true,
            format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must contain '@'" }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    
    if login
      where(conditions.to_h).where(
        ["lower(username) = :value OR lower(email) = :value", 
        { value: login.downcase }]
      ).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def to_param
    username
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update ]

  def index
    @filter = params[:filter] || "all"

    posts_scope = if @filter == "following" && current_user
                    Post.where(user_id: current_user.following_ids)
                  else
                    Post.all
                  end
  
    @posts = posts_scope
      .includes(:user, :likes, image_attachment: :blob)
      .with_attached_image
      .order(created_at: :desc)
      .paginate(page: params[:page], per_page: 20)
  
    @liked_post_ids = current_user.liked_posts.pluck(:id)
  end

  def show
    @post = Post.includes(:user, :likes, image_attachment: :blob)
      .with_attached_image
      .find(params[:id])
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @post_liked = @post.likes.exists?(user_id: current_user.id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to root_path unless @post.user == current_user
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save

        CompressImageJob.perform_later(@post.id)
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  
  def set_post
    @post = Post.find(params.expect(:id))
  end

  def post_params
    params.expect(post: [ :user_id, :description, :image ]).merge({ user_id: current_user.id })
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
<div class="post-show-container">
  <div class="image-panel">
    <%= link_to (request.referer || posts_path), class: "button" do %>
      <%= image_tag "arrow_back.svg", alt: "back", style: "height: 18px; width: 8px;", class: "bg-transparent" %>
      <div class="button-text">
        Back
      </div>
    <% end %>
    <div class="add-image-container">
      <div class="default-text">Select photo on your computer</div>
      <label class="file-upload-button">
        <%= form.file_field :image, class: "file-input", accept: "image/jpeg, image/png" %>
        Select file on computer
      </label>
      <div class="default-text" id="selected-file" display="none"></div>
    </div>
  </div>
  <%= render partial: "shared/description_panel", locals: { form: form, post: post } %>
</div>

<script>
  document.addEventListener("turbo:load", () => {
    const inputFile = document.querySelector('input[type="file"]');
    const fileText = document.querySelector("#selected-file");
    inputFile.addEventListener('change', (e) => {
      let file = e.target.files[0];
      if (file.type !== "image/jpeg" && file.type !== "image/png") {
        fileText.innerHTML = "Only JPEG and PNG images are allowed!";
        e.preventDefault();
      } else {
        fileText.innerHTML = `Selected file: ${file.name}`;
      }
    });
  });
</script>
<% end %>

app/views/posts/_post.html.erb
<div class="post-show-container bg2c" id="<%= dom_id post %>">
  <div class="image-panel bg2c" style="margin: 0px">
    <%= image_tag(post.image, class: "post-image-mini bg2c") %>
  </div>
  <div class="post-info-panel bg2c" style="margin: 0px; width: 308px;">
    <div class="post-info bg2c"> 
      <%= image_tag "profile.svg", alt: "profile image", class: "profile-image bg2c" %>
      <div class="post-profile-date-likes bg2c">
        <div class="post-profile-date bg2c">
          <%= link_to user_path(post.user), class: "post-profile bg2c" do %>
            <%= post.user.username %>
          <% end %>
          <div class="post-date bg2c">
            <%= post.created_at.to_date %>
          </div>
        </div>
      </div>
    </div>
    <div class="post-description bg2c">
      <%= post.description %>
    </div>
    <div class="post-buttons">
      <div data-controller="like" data-like-post-id-value="<%= post.id %>">
        <%= check_box_tag "like_toggle_#{post.id}", "1", @liked_post_ids.include?(post.id),
              id: "like-toggle-#{post.id}", class: "hidden-checkbox",
              data: { action: "change->like#toggle" } %>
        <label for="like-toggle-<%= post.id %>" class="button">
          <%= image_tag "like.svg", alt: "like", style: "height: 20px; width: 22.55px;", class: "bg-transparent" %>
          <div class="button-text" data-like-target="count">
            <%= post.likes.size %>
          </div>
        </label>
      </div>
      <%= link_to post_path(post), class: "button" do %>
        <div class="button-text">
          Go to post
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= form_with(model: @post) do |form| %>
<div class="post-show-container">
  <div class="image-panel">
    <%= link_to (request.referer || posts_path), class: "button" do %>
      <%= image_tag "arrow_back.svg", alt: "back", style: "height: 18px; width: 8px;", class: "bg-transparent" %>
      <div class="button-text">
        Back
      </div>
    <% end %>
    <%= image_tag(@post.image, class: "post-image") %>
  </div>
  <%= render partial: "shared/description_panel", locals: { form: form, post: @post } %>
</div>
<% end %>

app/views/posts/index.html.erb
<% content_for :page_title, "Feed" %>

<%= render 'shared/left_panel' %>
<div id="posts" class="content-posts">
  <div class="feed-filters" data-controller="feed-filter" style="margin-bottom: -60px">
    <%= form_with url: posts_path, class: "filter-buttons", method: :get, data: { turbo_frame: "posts" } do %>
      <%= radio_button_tag :filter, "all", @filter == "all", id: "filter_all", class: "hidden-radio", data: { action: "change->feed-filter#submit" } %>
      <label for="filter_all" class="button">All posts</label>
  
      <%= radio_button_tag :filter, "following", @filter == "following", id: "filter_following", class: "hidden-radio", data: { action: "change->feed-filter#submit" } %>
      <label for="filter_following" class="button">Following</label>
    <% end %>
  </div>
  

  <% if @posts.size != 0 %>

  <%= turbo_frame_tag "posts" %>
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
    <%= will_paginate @posts, class: "pagination" %>
  </%= turbo_frame_tag %>

  <% else %>

  <div class="settings-elem" style="margin-top: 40px">
    <p>There are no posts yet. Follow someone to view their posts!</p>
  </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<% content_for :page_title, "New post" %>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<% content_for :page_title, "View post" %>

<div class="post-show-container">
  <div class="image-panel">
    <%= link_to (request.referer || posts_path), class: "button" do %>
      <%= image_tag "arrow_back.svg", alt: "back", style: "height: 18px; width: 8px;", class: "bg-transparent" %>
      <div class="button-text">
        Back
      </div>
    <% end %>
    <%= image_tag(@post.image, class: "post-image") %>
  </div>
  
  <div class="post-info-panel">
    <div class="post-info">
      <%= image_tag "profile.svg", alt: "profile image", class: "profile-image" %>
      <div class="post-profile-date-likes">
        <div class="post-profile-date">
          <%= link_to user_path(@post.user), class: "post-profile" do %>
            <%= @post.user.username %>
          <% end %>
          <div class="post-date">
            <%= @post.created_at.to_date %>
          </div>
        </div>
        <div data-controller="like" data-like-post-id-value="<%= @post.id %>">
          <%= check_box_tag "like_toggle_#{@post.id}", "1", @post_liked,
                id: "like-toggle-#{@post.id}", class: "hidden-checkbox",
                data: { action: "change->like#toggle" } %>
          <label for="like-toggle-<%= @post.id %>" class="button">
            <%= image_tag "like.svg", alt: "like", style: "height: 20px; width: 22.55px;", class: "bg-transparent" %>
            <div class="button-text" data-like-target="count">
              <%= @post.likes.size %>
            </div>
          </label>
        </div>
      </div>
    </div>
    <div class="post-description">
      <%= @post.description %>
    </div>
    <div data-controller="comment" data-comment-post-id-value="<%= @post.id %>" class="post-info-panel" style="margin-top: 0px;">
      <div class="textarea-container">
        <textarea name="comment" id="comment" placeholder="Leave a comment..." maxlength="200" rows="4" class="comment-textarea" data-comment-target="textarea"></textarea>
        <div class="hint-text" style="align-self: flex-end" data-comment-target="hintText">0/200</div>
        <input type="hidden" value="<%= @post.id %>" data-comment-target="postId">
        <button type="button" class="button" data-action="click->comment#submitComment">Send</button>
      </div>
      <% if @post.user == current_user %>
        <%= link_to "Edit post", edit_post_path(@post), class: "link", style: "align-self: flex-end" %>
      <% end %>

      <div id="comments-list" class="comments-container">
        <% @comments.each do |comment| %>
          <div class="comment" data-comment-id="<%= comment.id %>">
            <div class="post-info">
              <%= image_tag "profile.svg", alt: "profile image", class: "profile-image" %>
              <div class="post-profile-date-likes">
                <div class="post-profile-date">
                  <%= link_to user_path(comment.user), class: "post-profile" do %>
                    <%= comment.user.username %>
                  <% end %>
                  <div class="comment-date">
                    <%= comment.created_at.to_date %>
                    <% if comment.user == current_user %>
                      <%= image_tag "delete.svg",
                        alt: "delete",
                        class: "delete-button",
                        data: {
                          action: "click->comment#deleteComment"
                        } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="post-description">
              <%= comment.value %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("turbo:load", () => {
    const textarea = document.querySelector(".comment-textarea");
    const hintText = document.querySelector(".hint-text");

    if (textarea && hintText) {
      textarea.addEventListener('input', (e) => {
        hintText.innerHTML = `${e.target.value.length}/200`;
      });
    }
  });
</script>